### ISSUE TITLE
Custom Change Hotkey ??

### ISSUE THREAD

**Issue by nguyenvancaoky** [globalpolicy/pubgmobilemousehelper#3]
Can you add Custom Change Hotkey ?
thank.

**Comment by nguyenvancaoky** [comment]
i try build code with vs 2015 and program show 105 errors :(

**Comment by nguyenvancaoky** [comment]
![image](https://user-images.githubusercontent.com/26179692/42486098-b3248e3e-8424-11e8-8842-ddf190da855c.png)

**Comment by globalpolicy** [comment]
Check the version 2.2 update. 
The hotkeys for anti-recoil toggle and program activation are fixed for the moment because one wouldn't need use them that often.
However, three more keys for firing have been added (CTRL, SHIFT, RMB) besides scroll wheel seeing as this is more relevant during gameplay.
